# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9110200d76866467b6a1ba41796a101aad30e3406a242490253a714f066a652299984ab4165bf7106ce75fa811234df9d725a82b2476a530bb8193b6b67e229

test:
  secret_key_base: c88cf47ee0a559cdcec139588f96e43f6a60ec572b409fe6eb43e3b4e3a7e98e5aad34ef9c58240e675ec91281e70351d1da45e19b1fc1d07a8d0f477bb1190f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
